name: Deploy assets

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build artifacts
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2

    - name: Install dependencies
      run: npm install

    - name: Run linting
      run: npm run lint

    - name: Build assets
      run: npm run build
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: ./dist

  deploy:
    name: Deploy artifacts
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: dist

    - name: S3 sync
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-1'
        SOURCE_DIR: './dist'
        DEST_DIR: 'webmapping/int/tree'
